apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-frontend
  namespace: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp-frontend
  template:
    metadata:
      labels:
        app: bankapp-frontend
    spec:
      containers:
        - name: frontend
<<<<<<< HEAD
          image: sahilmahat/bankapp-frontend:14
=======
          image: sahilmahat/bankapp-frontend:latest
>>>>>>> 496f6ea (added changes in k8s and frontend)
          ports:
            - containerPort: 80

